name: CI

on:
  workflow_dispatch:
    

jobs:
  win-server:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Runs a single command using the runners shell
    - name: cloudflared
      shell: pwsh # 指定在 Windows 中使用 PowerShell
      run: |
        echo "cloudflared start"
        curl.exe -JLO https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe
        ls
        ./cloudflared-windows-amd64.exe service install ${{ secrets.CLOUD }}
        net user runneradmin ${{ secrets.RUNNERAD }}
        echo "end "

    - name: code-server
      shell: pwsh # 指定在 Windows 中使用 PowerShell
      if: true
      # ~/AppData/Roaming/code-server
      # cat ~/AppData/Roaming/code-server/config.yaml
      # Start-Process -FilePath "code-server.exe" -NoNewWindow
      # dirPath="C:\Users\runneradmin\AppData\Roaming\code-server\Config\config.yaml"       
      run: |
        echo "code-server start"
        npm install --global code-server --unsafe-perm
        mkdir -p ~/.config/code-server
        touch C:\Users\runneradmin\AppData\Roaming\code-server\Config\config.yaml        
        echo "bind-addr: 127.0.0.1:8080" > C:\Users\runneradmin\AppData\Roaming\code-server\Config\config.yaml
        echo "auth: password" >> C:\Users\runneradmin\AppData\Roaming\code-server\Config\config.yaml
        echo "password: ${{ secrets.CODE }}" >> C:\Users\runneradmin\AppData\Roaming\code-server\Config\config.yaml
        echo "cert: false" >> C:\Users\runneradmin\AppData\Roaming\code-server\Config\config.yaml   
        code-server        
        echo "end "

    - name: Don't kill instace     
      shell: pwsh # 指定在 Windows 中使用 PowerShell   
      run: |
        echo "sleep start"
        sleep 20880
        echo "sleep end"

