name: CI

on:
  workflow_dispatch:
    

jobs:
  win-server:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Runs a single command using the runners shell
    - name: cloudflared
      shell: pwsh # 指定在 Windows 中使用 PowerShell
      run: |
        echo "cloudflared start"
        curl.exe -JLO https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe
        ls
        ./cloudflared-windows-amd64.exe service install ${{ secrets.CLOUD }}
        net user runneradmin ${{ secrets.RUNNERAD }}
        echo "end "

    - name: code-server
      shell: pwsh # 指定在 Windows 中使用 PowerShell
      run: |
        echo "code-server start"
        npm install --global code-server --unsafe-perm
        ls ~/.config/code-server
        code-server
        cat ~/.config/code-server/config.yaml
        echo "end "

    - name: Don't kill instace     
      shell: pwsh # 指定在 Windows 中使用 PowerShell   
      run: |
        echo "sleep start"
        sleep 3600
        echo "sleep end"

