name: CI

on:
  workflow_dispatch:
    

jobs:
  greet:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Runs a single command using the runners shell
    - name: Send greeting
      shell: pwsh # 指定在 Windows 中使用 PowerShell
      run: |
        echo "Hello "
        curl.exe -O https://github.com/cloudflare/cloudflared/releases/download/2024.3.0/cloudflared-windows-amd64.exe
        ls
        echo "end "

